package com.bookshelf.app.dashboard.data.tables

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing book-related data stored in the database.
 *
 * @param id The unique identifier of the book entry (auto-generated by default).
 * @param uid The unique identifier associated with the book.
 * @param image The URL or path to the book's image.
 * @param score The score or rating of the book.
 * @param popularity The popularity of the book.
 * @param title The title of the book.
 * @param publishedChapterDate The date when a chapter of the book was published (in milliseconds).
 */
@Entity(tableName = "tbl_books_data")
data class BooksEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val uid: String?,
    val image: String?,
    val score: Double?,
    val popularity: Int?,
    val title: String?,
    val publishedChapterDate: Long?,
)